# Generated by Django 6.0.3 on 2026-03-04 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
